<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fr.soe.a3s</groupId>
    <artifactId>ArmA3Sync</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- Dependencies -->
        <commons.io.version>2.0.1</commons.io.version>
        <commons.net.version>3.4</commons.net.version>
        <dom4j.version>1.6.1</dom4j.version>
        <jaxen.version>1.1-beta-6</jaxen.version>
        <jtattoo.version>1.6.10</jtattoo.version>
        <jaxb.api.version>2.3.1</jaxb.api.version>
        <commons.lang3.version>3.17.0</commons.lang3.version>
        <junique.version>1.0.4</junique.version>
        <jshortcut.version>0.4-oberzalek</jshortcut.version>
        <netbeans.swing.outline.version>RELEASE73</netbeans.swing.outline.version>
        <!-- Plugins -->
        <maven.compiler.plugin.version>3.8.1</maven.compiler.plugin.version>
        <maven.assembly.plugin.version>3.7.1</maven.assembly.plugin.version>
        <maven.install.plugin.version>3.1.2</maven.install.plugin.version>
        <maven.versions.plugin.version>2.18.0</maven.versions.plugin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons.io.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId>
            <version>${commons.net.version}</version>
        </dependency>
        <dependency>
            <groupId>dom4j</groupId>
            <artifactId>dom4j</artifactId>
            <version>${dom4j.version}</version>
        </dependency>
        <dependency>
            <groupId>jaxen</groupId>
            <artifactId>jaxen</artifactId>
            <version>${jaxen.version}</version>
        </dependency>
        <dependency>
            <groupId>com.jtattoo</groupId>
            <artifactId>JTattoo</artifactId>
            <version>${jtattoo.version}</version>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>${jaxb.api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons.lang3.version}</version>
        </dependency>
        <!--
        Local dependencies that are not present in Maven Central
        and are installed into local maven repository from dependencies folder using maven-install-plugin
        -->
        <dependency>
            <groupId>it.sauronsoftware</groupId>
            <artifactId>junique</artifactId>
            <version>${junique.version}</version>
        </dependency>
        <dependency>
            <groupId>net.jimmc</groupId>
            <artifactId>jshortcut</artifactId>
            <version>${jshortcut.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-swing-outline</artifactId>
            <version>${netbeans.swing.outline.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>${maven.versions.plugin.version}</version>
            </plugin>
            <!-- Build an executable JAR -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>${maven.assembly.plugin.version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <archive>
                                <manifest>
                                    <mainClass>
                                        fr.soe.a3s.main.ArmA3Sync
                                    </mainClass>
                                </manifest>
                            </archive>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Install jars from dependencies folder into local maven repository before compile -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>${maven.install.plugin.version}</version>
                <executions>
                    <execution>
                        <id>install-jar-jshortcut</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>validate</phase>
                        <configuration>
                            <groupId>net.jimmc</groupId>
                            <artifactId>jshortcut</artifactId>
                            <version>0.4-oberzalek</version>
                            <packaging>jar</packaging>
                            <file>${project.basedir}/dependencies/jshortcut-0.4-oberzalek.jar</file>
                            <generatePom>true</generatePom>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-jar-junique</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>validate</phase>
                        <configuration>
                            <groupId>it.sauronsoftware</groupId>
                            <artifactId>junique</artifactId>
                            <version>1.0.4</version>
                            <packaging>jar</packaging>
                            <file>${project.basedir}/dependencies/junique-1.0.4.jar</file>
                            <generatePom>true</generatePom>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-jar-netbeans-swing-outline</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>validate</phase>
                        <configuration>
                            <groupId>org.netbeans.api</groupId>
                            <artifactId>org-netbeans-swing-outline</artifactId>
                            <version>RELEASE73</version>
                            <packaging>jar</packaging>
                            <file>${project.basedir}/dependencies/org-netbeans-swing-outline-RELEASE73.jar</file>
                            <generatePom>true</generatePom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>